language: c
sudo: false

<<<<<<< HEAD
matrix:
  include:
    - os: linux
      env: C_COMPILER=gcc CXX_COMPILER=g++
    - os: linux
      env: C_COMPILER=clang CXX_COMPILER=clang++
=======
compiler:
  - gcc
  - clang
>>>>>>> 7605df11f39f3fcde53a31c68def6ef44c320f6a

addons:
  apt:
    packages:
      - libgtest-dev

before_install:
  - pip install --user cpp-coveralls
<<<<<<< HEAD
  - export CC=$(C_COMPILER)
  - export CXX=$(CXX_COMPILER)
=======
>>>>>>> 7605df11f39f3fcde53a31c68def6ef44c320f6a

install:
  - mkdir ~/gtest
  - cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ /usr/src/gtest/
  - make CC=$(CC) CXX=$(CXX)
  - cd -

script:
  - cd src
  - ./make.bash
  - cd ../tests
  - make test CC=$(CC) CXX=$(CXX)
  - mv *.gcno ../
  - cd ..

after_success:
  - coveralls --exclude tests --gcov-options '\-lp'
